name: CI - Continuous Integration

on:
  push:
    branches: [ develop, feature/*, fix/*, hotfix/* ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  quick-check:
    runs-on: ubuntu-latest
    name: Quick Quality Check
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: true
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Check formatting
        run: dart format --output=none --set-exit-if-changed .
        
      - name: Analyze code
        run: flutter analyze --fatal-infos
        
      - name: Run tests
        run: flutter test
        
      - name: Build APK (Debug only)
        run: flutter build apk --debug
        
      - name: Upload Debug APK for Testing
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk-${{ github.sha }}
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7
          
      - name: Comment PR with download link
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const comment = `## 🔧 APK de Teste Disponível
            
            Um APK de debug foi gerado para este Pull Request e está disponível para download nos artefatos da action.
            
            ### 📱 Como testar:
            1. Vá para a aba "Actions" deste PR
            2. Clique no workflow "CI - Continuous Integration"
            3. Baixe o artefato "debug-apk-${{ github.sha }}"
            4. Instale o APK no seu dispositivo Android
            
            ### ⚠️ Nota:
            Este é um build de debug - apenas para testes internos.
            
            **Commit:** \`${{ github.sha }}\`
            **Branch:** \`${{ github.head_ref }}\``;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });