name: Deploy APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: true
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Run tests
        run: flutter test
        
      - name: Analyze code
        run: flutter analyze
        
      - name: Build APK (Debug)
        run: flutter build apk --debug
        
      - name: Build APK (Release)
        run: flutter build apk --release
        
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: planilha-ehtudo-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 30
          
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: planilha-ehtudo-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 90
          
      - name: Create Release (on main/master branch)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            Automated release from commit ${{ github.sha }}
            
            ## Changes
            - Built from branch: ${{ github.ref_name }}
            - Commit: ${{ github.sha }}
            
            ## Downloads
            - `app-release.apk`: Production-ready APK
            - `app-debug.apk`: Debug version for testing
            
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/flutter-apk/app-debug.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}